## ===============================
## = DATABASE CONFIGURATION =
## ===============================
## i have used port forwarding concept to connect to vm port 3306 on which sql is running
## my vm details ubuntu
#ubuntu user-> vboxuser
#ubuntu pass -> 12345
#kafka
#user->kafak
#password->12345


